// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/job.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobPosting represents a single job scraping result.
type JobPosting struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the job, likely composed of source and ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// content of the job title.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Department or ministry offering the job.
	Department string `protobuf:"bytes,3,opt,name=department,proto3" json:"department,omitempty"`
	// Location of the job.
	Location string `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	// URL to the job posting or PDF.
	Url string `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	// Date of the job posting or deadline.
	Date          string `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobPosting) Reset() {
	*x = JobPosting{}
	mi := &file_proto_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobPosting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobPosting) ProtoMessage() {}

func (x *JobPosting) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobPosting.ProtoReflect.Descriptor instead.
func (*JobPosting) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{0}
}

func (x *JobPosting) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobPosting) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JobPosting) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *JobPosting) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *JobPosting) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *JobPosting) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

// JobList is a wrapper for a list of jobs, suitable for serialization.
type JobList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of job postings.
	Jobs []*JobPosting `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	// Unix timestamp of when the list was last updated.
	LastUpdated   int64 `protobuf:"varint,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobList) Reset() {
	*x = JobList{}
	mi := &file_proto_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobList) ProtoMessage() {}

func (x *JobList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobList.ProtoReflect.Descriptor instead.
func (*JobList) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{1}
}

func (x *JobList) GetJobs() []*JobPosting {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *JobList) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

var File_proto_job_proto protoreflect.FileDescriptor

const file_proto_job_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/job.proto\x12\x06models\"\x94\x01\n" +
	"\n" +
	"JobPosting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1e\n" +
	"\n" +
	"department\x18\x03 \x01(\tR\n" +
	"department\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x12\n" +
	"\x04date\x18\x06 \x01(\tR\x04date\"T\n" +
	"\aJobList\x12&\n" +
	"\x04jobs\x18\x01 \x03(\v2\x12.models.JobPostingR\x04jobs\x12!\n" +
	"\flast_updated\x18\x02 \x01(\x03R\vlastUpdatedB/Z-github.com/entreya/job-aggregation/pkg/modelsb\x06proto3"

var (
	file_proto_job_proto_rawDescOnce sync.Once
	file_proto_job_proto_rawDescData []byte
)

func file_proto_job_proto_rawDescGZIP() []byte {
	file_proto_job_proto_rawDescOnce.Do(func() {
		file_proto_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_job_proto_rawDesc), len(file_proto_job_proto_rawDesc)))
	})
	return file_proto_job_proto_rawDescData
}

var file_proto_job_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_job_proto_goTypes = []any{
	(*JobPosting)(nil), // 0: models.JobPosting
	(*JobList)(nil),    // 1: models.JobList
}
var file_proto_job_proto_depIdxs = []int32{
	0, // 0: models.JobList.jobs:type_name -> models.JobPosting
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_job_proto_init() }
func file_proto_job_proto_init() {
	if File_proto_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_job_proto_rawDesc), len(file_proto_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_job_proto_goTypes,
		DependencyIndexes: file_proto_job_proto_depIdxs,
		MessageInfos:      file_proto_job_proto_msgTypes,
	}.Build()
	File_proto_job_proto = out.File
	file_proto_job_proto_goTypes = nil
	file_proto_job_proto_depIdxs = nil
}
